apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-storage
  labels:
    app: mysql
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /dir/container1/
    server: 172.31.12.214
