apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment1
spec:
  replicas: 5
  selector:
    matchLabels:
      app: deployment1
  template:
    metadata:
      labels:
        app: deployment1
    spec:
      containers:
      - name: deployment1
        image: nginx:latest
        ports:
        - containerPort: 80
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nodeos
                operator: In
                values:
                - amzlinux 
          