apiVersion: v1
kind: Pod
metadata:
  name: pod1tint
  labels:
    name: pod1tint
spec:
  containers:
  - name: pod1tint
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    nodeSelector: 
        nodepurpose: mgmt  
