# deploy storge 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fullapp-pv-vol
  labels:
    app: fullapp
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/container1"

# Deploy pvc storge 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fullapp-pvc-claim
  labels:
    app: fullapp
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

# deploy applications
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fullapp
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: fullapp
  template:
    metadata:
      labels:
        app: fullapp
    spec:
      containers:
      - name: fullapp
        image: nginx:latest
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "800Mi"
            cpu: "800m"
        ports:
        - containerPort: 80
        volumeMounts:
          - name:  storageapp
            mountPath: /usr/share/nginx/html/
      volumes:
        - name: storageapp
          persistentVolumeClaim:
            claimName: fullapp-pvc-claim
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nodeos
                operator: In
                values:
                - amzlinux   

